OENIK_PROG3_2020_2_ZJXJG3/BirthdayPartyService.Web/Models/BirthdayService.cs
// <copyright file="BirthdayService.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace BirthdayPartyService.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// This is the BirthdayService class.
    /// </summary>
    public class BirthdayService
    {
        /// <summary>
        /// Gets or sets the ID of the service.
        /// </summary>
        [Display(Name = "Service id")]
        [Required]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the name of the service.
        /// </summary>
        [Display(Name = "Service name")]
        [Required]
        [StringLength(100)]
        public string ServiceName { get; set; }

        /// <summary>
        /// Gets or sets the price of the service.
        /// </summary>
        [Display(Name = "Service price")]
        [Required]
        public int Price { get; set; }

        /// <summary>
        /// Gets or sets the recommended min age of the service.
        /// </summary>
        [Display(Name = "Recommended minimum age")]
        [Required]
        public int MinAge { get; set; }

        /// <summary>
        /// Gets or sets the recommended max age of the service.
        /// </summary>
        [Display(Name = "Recommended maximum age")]
        [Required]
        public int MaxAge { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the service can be held indoor or not.
        /// </summary>
        [Display(Name = "Is it indoor?")]
        [Required]
        public bool IsIndoor { get; set; }

        /// <summary>
        /// Gets or sets the recommendation of the service.
        /// </summary>
        [Display(Name = "Service recommendation")]
        [Required]
        [Range(1, 10)]
        public int Recommendation { get; set; }
    }
}

OENIK_PROG3_2020_2_ZJXJG3/BirthdayPartyService.Web/Models/BirthdayServiceViewModel.cs
// <copyright file="BirthdayServiceViewModel.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace BirthdayPartyService.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// This is the viewmodel class.
    /// </summary>
    public class BirthdayServiceViewModel
    {
        /// <summary>
        /// Gets or sets the edited service instance.
        /// </summary>
        public BirthdayService EditedService { get; set; }

        /// <summary>
        /// Gets or sets the list of services.
        /// </summary>
        public List<BirthdayService> ListOfServices { get; set; }
    }
}

OENIK_PROG3_2020_2_ZJXJG3/BirthdayPartyService.Web/Controllers/BirthdayServicesController.cs
// <copyright file="BirthdayServicesController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace BirthdayPartyService.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AutoMapper;
    using BirthdayPartyService.Data.Models;
    using BirthdayPartyService.Logic;
    using BirthdayPartyService.Web.Models;
    using Microsoft.AspNetCore.Mvc;

    /// <summary>
    /// This is the controller class.
    /// </summary>
    public class BirthdayServicesController : Controller
    {
        private ICompanyLogic companyLogic;
        private IVisibleContentLogic visibleLogic;
        private IMapper mapper;
        private BirthdayServiceViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="BirthdayServicesController"/> class.
        /// </summary>
        /// <param name="companyLogic">The parameter is an icompanylogic object.</param>
        /// <param name="visibleLogic">The parameter is an ivisiblecontent object.</param>
        /// <param name="mapper">The parameter is an imapper object.</param>
        public BirthdayServicesController(ICompanyLogic companyLogic, IVisibleContentLogic visibleLogic, IMapper mapper)
        {
            this.companyLogic = companyLogic;
            this.visibleLogic = visibleLogic;
            this.mapper = mapper;

            this.vm = new BirthdayServiceViewModel();
            this.vm.EditedService = new Models.BirthdayService();

            var birthdayservices = visibleLogic.GetAllServices();
            this.vm.ListOfServices = mapper.Map<IList<Data.Models.ServiceOptions>, List<Models.BirthdayService>>(birthdayservices);
        }

        /// <summary>
        /// This is an Index method.
        /// </summary>
        /// <returns>Returns a view.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("BirthdayServicesIndex", this.vm);
        }

        /// <summary>
        /// This is the details method.
        /// </summary>
        /// <returns>Returns a view.</returns>
        /// <param name="id">The parameter is the id.</param>
        public IActionResult Details(int id)
        {
            return this.View("BirthdayServicesDetails", this.GetBirthdayServiceModel(id));
        }

        /// <summary>
        /// This is the remove method.
        /// </summary>
        /// <returns>Returns a view.</returns>
        /// <param name="id">The parameter is the id.</param>
        public IActionResult Remove(int id)
        {
            this.TempData["editResult"] = "Delete FAIL";
            if (this.companyLogic.DeleteServiceBool(id))
            {
                this.TempData["editResult"] = "Delete OK";
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// This is the edit method.
        /// </summary>
        /// <returns>Returns a view.</returns>
        /// <param name="id">The parameter is the id.</param>
        public IActionResult Edit(int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.vm.EditedService = this.GetBirthdayServiceModel(id);
            return this.View("BirthdayServicesIndex", this.vm);
        }

        /// <summary>
        /// This is another edit method.
        /// </summary>
        /// <param name="bservice">The parameter is a birthdayservice object.</param>
        /// <param name="editAction">The parameter is a string.</param>
        /// <returns>Returns a view.</returns>
        [HttpPost]
        public IActionResult Edit(Models.BirthdayService bservice, string editAction)
        {
            if (this.ModelState.IsValid && bservice != null)
            {
                this.TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    try
                    {
                        this.companyLogic.InsertNewService(bservice.ServiceName, bservice.Price, bservice.MinAge, bservice.MaxAge, bservice.Recommendation, bservice.IsIndoor);
                    }
                    catch (FormatException ex)
                    {
                        this.TempData["editResult"] = "Edit FAIL:" + ex.Message;
                    }
                }
                else
                {
                    ServiceOptions newservice = new ServiceOptions();
                    newservice.Id = bservice.Id;
                    newservice.Name = bservice.ServiceName;
                    newservice.Price = bservice.Price;
                    newservice.RecommendedMinAge = bservice.MinAge;
                    newservice.RecommendedMaxAge = bservice.MaxAge;
                    newservice.Indoor = bservice.IsIndoor;
                    newservice.Recommendation = bservice.Recommendation;

                    if (!this.companyLogic.ChangeServiceFullBool(newservice.Id, newservice))
                    {
                        this.TempData["editResult"] = "Edit FAIL";
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.TempData["editResult"] = "Edit";
                this.vm.EditedService = bservice;
                return this.View("BirthdayServicesIndex", this.vm);
            }
        }

        private Models.BirthdayService GetBirthdayServiceModel(int id)
        {
            Data.Models.ServiceOptions oneService = this.visibleLogic.GetOneService(id);
            return this.mapper.Map<Data.Models.ServiceOptions, Models.BirthdayService>(oneService);
        }
    }
}

OENIK_PROG3_2020_2_ZJXJG3/BirthdayPartyService.Web/Views/BirthdayServices/BirthdayServicesDetails.cshtml
@model BirthdayPartyService.Web.Models.BirthdayService

@{ 
    ViewData["Title"] = "BirthdayServicesDetails";
}

<h2>Datasheet of one birthday party service</h2>

@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Id)</td>
        <td>@Html.DisplayFor(m => m.Id)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.ServiceName)</td>
        <td>@Html.DisplayFor(m => m.ServiceName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Price)</td>
        <td>@Html.DisplayFor(m => m.Price)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.MinAge)</td>
        <td>@Html.DisplayFor(m => m.MinAge)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.MaxAge)</td>
        <td>@Html.DisplayFor(m => m.MaxAge)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.IsIndoor)</td>
        <td>@Html.DisplayFor(m => m.IsIndoor)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Recommendation)</td>
        <td>@Html.DisplayFor(m => m.Recommendation)</td>
    </tr>
</table>

OENIK_PROG3_2020_2_ZJXJG3/BirthdayPartyService.Web/Views/BirthdayServices/BirthdayServicesEdit.cshtml
@model BirthdayPartyService.Web.Models.BirthdayService

<h2>Birthday service Editor</h2>

@using (Html.BeginForm("Edit", "BirthdayServices"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id)

    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.ServiceName)</div>
    <div class="editor-field">@Html.EditorFor(m => m.ServiceName)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Price)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Price)</div>

    <div class="editor-label">@Html.LabelFor(m => m.MinAge)</div>
    <div class="editor-field">@Html.EditorFor(m => m.MinAge)</div>

    <div class="editor-label">@Html.LabelFor(m => m.MaxAge)</div>
    <div class="editor-field">@Html.EditorFor(m => m.MaxAge)</div>

    <div class="editor-label">@Html.LabelFor(m => m.IsIndoor)</div>
    <div class="editor-field">@Html.EditorFor(m => m.IsIndoor)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Recommendation)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Recommendation)</div>

    <input type="submit" value="SEND" />
}

OENIK_PROG3_2020_2_ZJXJG3/BirthdayPartyService.Web/Views/BirthdayServices/BirthdayServicesIndex.cshtml
@model BirthdayPartyService.Web.Models.BirthdayServiceViewModel

@{
    ViewData["Title"] = "BirthdayServicesIndex";
}

<h2>Birthday party services official webpage</h2>

<p style="color:mediumvioletred">@TempData["editResult"]</p>

@await Html.PartialAsync("BirthdayServicesEdit", Model.EditedService)

@await Html.PartialAsync("BirthdayServicesList", Model.ListOfServices)

OENIK_PROG3_2020_2_ZJXJG3/BirthdayPartyService.Web/Views/BirthdayServices/BirthdayServicesList.cshtml
@model IEnumerable<BirthdayPartyService.Web.Models.BirthdayService>

<h2>Birthday Party Services List</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database!</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().ServiceName)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.ServiceName)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.Id })</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.Id })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.Id })</td>
            </tr>
        }
    </table>
}